/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package helpboard;

import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author mina
 */
public class mainpage extends javax.swing.JFrame {

    public mainpage() {
        initComponents();
        setVisible(true); /*1_창표시하기*/
        setLocationRelativeTo(null); // 스크린 중앙에 배치하기 
        setTitle("HELP BOARD - main page");
        timePanel.setVisible(false); //표 가리기
        cafeteriaPanel.setVisible(false); //표 가리기
        calendarPanel.setVisible(false); //표 가리기
        todoListPanel.setVisible(false); 
        // mypage_id.getText(real_ID);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradiente1 = new design.PanelGradiente();
        panelBorder1 = new design.PanelBorder();
        jLabel2 = new javax.swing.JLabel();
        todolistBtn = new design.RoundedButton();
        mypage_id = new javax.swing.JLabel();
        calendarBtn = new design.RoundedButton();
        jLabel6 = new javax.swing.JLabel();
        timesheduleBtn = new design.RoundedButton();
        cafeteriaBtn = new design.RoundedButton();
        hideBtn = new design.RoundedButton();
        jLabel8 = new javax.swing.JLabel();
        panelBorder3 = new design.PanelBorder();
        titleText = new javax.swing.JLabel();
        timePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        timeTable = new javax.swing.JTable();
        cafeteriaPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cafeteriaTable = new javax.swing.JTable();
        calendarPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        calendarTable = new javax.swing.JTable();
        todoListPanel = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        panelGradiente1.setColorPrimario(new java.awt.Color(255, 255, 102));
        panelGradiente1.setColorSecundario(new java.awt.Color(102, 255, 102));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("ID");

        todolistBtn.setBackground(new java.awt.Color(255, 255, 204));
        todolistBtn.setText("TO-DO");
        todolistBtn.setFont(new java.awt.Font("HY중고딕", 3, 14)); // NOI18N
        todolistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todolistBtnActionPerformed(evt);
            }
        });

        mypage_id.setBackground(new java.awt.Color(255, 255, 255));
        mypage_id.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        mypage_id.setForeground(new java.awt.Color(0, 153, 51));
        mypage_id.setText("202110710");

        calendarBtn.setBackground(new java.awt.Color(255, 255, 204));
        calendarBtn.setText("캘린더");
        calendarBtn.setFont(new java.awt.Font("HY중고딕", 3, 14)); // NOI18N
        calendarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarBtnActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 51));
        jLabel6.setText("mypage");

        timesheduleBtn.setBackground(new java.awt.Color(255, 255, 204));
        timesheduleBtn.setText("시간표");
        timesheduleBtn.setFont(new java.awt.Font("HY중고딕", 3, 14)); // NOI18N
        timesheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timesheduleBtnActionPerformed(evt);
            }
        });

        cafeteriaBtn.setBackground(new java.awt.Color(255, 255, 204));
        cafeteriaBtn.setText("학식표");
        cafeteriaBtn.setFont(new java.awt.Font("HY중고딕", 3, 14)); // NOI18N
        cafeteriaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafeteriaBtnActionPerformed(evt);
            }
        });

        hideBtn.setBackground(new java.awt.Color(0, 153, 0));
        hideBtn.setForeground(new java.awt.Color(255, 255, 255));
        hideBtn.setText("돌아가기");
        hideBtn.setFont(new java.awt.Font("HY중고딕", 3, 14)); // NOI18N
        hideBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideBtnActionPerformed(evt);
            }
        });

        panelBorder1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder1.setLayer(todolistBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder1.setLayer(mypage_id, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder1.setLayer(calendarBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder1.setLayer(timesheduleBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder1.setLayer(cafeteriaBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder1.setLayer(hideBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cafeteriaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timesheduleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(todolistBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calendarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(mypage_id))
                            .addComponent(hideBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel6)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(48, 48, 48)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mypage_id))
                .addGap(26, 26, 26)
                .addComponent(timesheduleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cafeteriaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(calendarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(todolistBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hideBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        panelGradiente1.add(panelBorder1);
        panelBorder1.setBounds(60, 60, 270, 480);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("나눔고딕", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("안녕하세요. HELPBOARD에 오신걸 환영합니다. ");
        panelGradiente1.add(jLabel8);
        jLabel8.setBounds(660, 560, 380, 21);

        panelBorder3.setBackground(new java.awt.Color(244, 249, 242));

        titleText.setBackground(new java.awt.Color(255, 255, 255));
        titleText.setFont(new java.awt.Font("나눔고딕 ExtraBold", 3, 36)); // NOI18N
        titleText.setForeground(new java.awt.Color(0, 153, 51));

        timePanel.setBackground(new java.awt.Color(255, 255, 255));
        timePanel.setOpaque(false);

        timeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"09:00~10:00", "데이터베이스", null, null, null, null},
                {"10:00~11:00", "데이터베이스", "직업과진로", null, null, null},
                {"11:00~12:00", "데이터베이스", "직업과진로", null, null, null},
                {"12:00~13:00", null, null, null, null, null},
                {"13:00~14:00", "IT실무영어", "자바프로그래밍", null, null, null},
                {"14:00~15:00", "IT실무영어", "자바프로그래밍", null, null, null},
                {"15:00~16:00", null, null, null, "복지국가의이해", null},
                {"16:00~17:00", null, null, null, null, null},
                {"17:00~18:00", null, null, null, null, null}
            },
            new String [] {
                "시간", "월", "화", "수", "목", "금"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(timeTable);

        javax.swing.GroupLayout timePanelLayout = new javax.swing.GroupLayout(timePanel);
        timePanel.setLayout(timePanelLayout);
        timePanelLayout.setHorizontalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        timePanelLayout.setVerticalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );

        cafeteriaPanel.setBackground(new java.awt.Color(255, 255, 255));
        cafeteriaPanel.setOpaque(false);

        cafeteriaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"11.29", "돈코츠라멘 매운돈코츠라멘 야끼소바 타코야끼", "가께우동 김치우동 라면 라면 토핑 (택 1) (떡/치즈/만두)", "제육불고기덮밥 떡갈비마요덮밥 치킨마요덮밥 가츠동", "포크커틀릿 치즈돈가스 치킨커틀릿", "순대야채볶음 잡곡밥 다시마무국 실곤약야채무침 검은콩자반 깍두기 요구르트 / 숭늉"},
                {"11.30", "매운돈코츠라멘 야끼소바 타코야끼", "김치우동 라면 라면 토핑 (택 1) (떡/치즈/만두)", "가츠동", "치즈돈가스 치킨커틀릿", "강된장비빔밥 미역국 오징어초무침 버섯볶음 배추김치 사과 / 숭늉"},
                {"12.01", " 야끼소바 타코야끼", "라면 토핑 (택 1) (떡/치즈/만두)", "떡갈비마요덮밥 치킨마요덮밥 가츠동", "치킨커틀릿", "매운떡볶이 후리가께밥 덴까스장국 미니돈가스 그린빈스양파볶음 깍두기 찰떡쿠키 / 숭늉"},
                {"12.02", "타코야끼", "가께우동 김치우동 라면 라면 토핑 (택 1) (떡/치즈/만두)", "제치킨마요덮밥 ", "포크커틀릿 치즈돈가스 치킨커틀릿", "쌀국수 잡곡밥 춘권튀김 고추지 배추김치 망고파인애플주스 / 숭늉"}
            },
            new String [] {
                "날짜", "소담상", "속이찬새참", "덮밥", "바삭카츠", "교직원"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(cafeteriaTable);

        javax.swing.GroupLayout cafeteriaPanelLayout = new javax.swing.GroupLayout(cafeteriaPanel);
        cafeteriaPanel.setLayout(cafeteriaPanelLayout);
        cafeteriaPanelLayout.setHorizontalGroup(
            cafeteriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cafeteriaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cafeteriaPanelLayout.setVerticalGroup(
            cafeteriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );

        calendarPanel.setBackground(new java.awt.Color(255, 255, 255));
        calendarPanel.setOpaque(false);

        calendarTable.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        calendarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "1", "2", "3", "4", "5"},
                {"6", "7", "8", "9", "10", "11", "12"},
                {"13", "14", "15", "16", "17", "18", "19"},
                {"20", "21", "22", "23", "24", "25", "26"},
                {"27", "28", "29", "30", null, null, null}
            },
            new String [] {
                "일", "월", "화", "수", "목", "금", "토"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        calendarTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        calendarTable.setGridColor(new java.awt.Color(233, 233, 233));
        calendarTable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(calendarTable);

        javax.swing.GroupLayout calendarPanelLayout = new javax.swing.GroupLayout(calendarPanel);
        calendarPanel.setLayout(calendarPanelLayout);
        calendarPanelLayout.setHorizontalGroup(
            calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calendarPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        calendarPanelLayout.setVerticalGroup(
            calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calendarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );

        todoListPanel.setBackground(new java.awt.Color(255, 255, 255));
        todoListPanel.setOpaque(false);

        jCheckBox1.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jCheckBox1.setText("교양과제");

        jCheckBox2.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jCheckBox2.setSelected(true);
        jCheckBox2.setText("전공기말과제");

        jCheckBox3.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jCheckBox3.setText("영어단어암기");

        jCheckBox4.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jCheckBox4.setText("장보기");

        jCheckBox5.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jCheckBox5.setText("리포트작성");

        jCheckBox6.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jCheckBox6.setText("입금하기");

        jCheckBox7.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jCheckBox7.setText("도서관가기");

        jCheckBox8.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jCheckBox8.setText("스터디계획");

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jLabel1.setText("1");

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jLabel3.setText("2");

        jLabel4.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jLabel4.setText("3");

        jLabel5.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jLabel5.setText("4");

        jLabel7.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jLabel7.setText("5");

        jLabel9.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jLabel9.setText("7");

        jLabel10.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jLabel10.setText("8");

        jLabel11.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jLabel11.setText("6");

        javax.swing.GroupLayout todoListPanelLayout = new javax.swing.GroupLayout(todoListPanel);
        todoListPanel.setLayout(todoListPanelLayout);
        todoListPanelLayout.setHorizontalGroup(
            todoListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todoListPanelLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(todoListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todoListPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todoListPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todoListPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todoListPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(todoListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(todoListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );
        todoListPanelLayout.setVerticalGroup(
            todoListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todoListPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(todoListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(todoListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox3)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(todoListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(todoListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        panelBorder3.setLayer(titleText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder3.setLayer(timePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder3.setLayer(cafeteriaPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder3.setLayer(calendarPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder3.setLayer(todoListPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelBorder3Layout = new javax.swing.GroupLayout(panelBorder3);
        panelBorder3.setLayout(panelBorder3Layout);
        panelBorder3Layout.setHorizontalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder3Layout.createSequentialGroup()
                .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(titleText, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(timePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder3Layout.createSequentialGroup()
                    .addContainerGap(17, Short.MAX_VALUE)
                    .addComponent(cafeteriaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
            .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder3Layout.createSequentialGroup()
                    .addContainerGap(21, Short.MAX_VALUE)
                    .addComponent(calendarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBorder3Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(todoListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        panelBorder3Layout.setVerticalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titleText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(timePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder3Layout.createSequentialGroup()
                    .addContainerGap(71, Short.MAX_VALUE)
                    .addComponent(cafeteriaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25)))
            .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder3Layout.createSequentialGroup()
                    .addContainerGap(69, Short.MAX_VALUE)
                    .addComponent(calendarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)))
            .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder3Layout.createSequentialGroup()
                    .addContainerGap(79, Short.MAX_VALUE)
                    .addComponent(todoListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)))
        );

        panelGradiente1.add(panelBorder3);
        panelBorder3.setBounds(350, 60, 600, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cafeteriaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafeteriaBtnActionPerformed
        titleText.setText("학식당");
        cafeteriaPanel.setVisible(true);
        cafeteriaTable.setRowHeight(50);
        
       DefaultTableCellRenderer renderer =  (DefaultTableCellRenderer)cafeteriaTable.getTableHeader().getDefaultRenderer();
       renderer.setHorizontalAlignment(SwingConstants.CENTER);
       cafeteriaTable.getTableHeader().setDefaultRenderer(renderer);
    }//GEN-LAST:event_cafeteriaBtnActionPerformed

    private void timesheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timesheduleBtnActionPerformed

       titleText.setText("시간표");
       timePanel.setVisible(true);
       timeTable.setRowHeight(50);
       
       DefaultTableCellRenderer renderer =  (DefaultTableCellRenderer)timeTable.getTableHeader().getDefaultRenderer();
       renderer.setHorizontalAlignment(SwingConstants.CENTER);
       timeTable.getTableHeader().setDefaultRenderer(renderer);
       
    }//GEN-LAST:event_timesheduleBtnActionPerformed

    private void calendarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarBtnActionPerformed
       titleText.setText("캘린더           11월");
       calendarPanel.setVisible(true);
       calendarTable.setRowHeight(70);
       
       DefaultTableCellRenderer renderer =  (DefaultTableCellRenderer)calendarTable.getTableHeader().getDefaultRenderer();
       renderer.setHorizontalAlignment(SwingConstants.CENTER);
       calendarTable.getTableHeader().setDefaultRenderer(renderer);
       
       DefaultTableCellRenderer celAlignCenter = new DefaultTableCellRenderer();
       celAlignCenter.setHorizontalAlignment(JLabel.CENTER);
       calendarTable.getColumn("일").setCellRenderer(celAlignCenter);
       calendarTable.getColumn("월").setCellRenderer(celAlignCenter);
       calendarTable.getColumn("화").setCellRenderer(celAlignCenter);      
       calendarTable.getColumn("수").setCellRenderer(celAlignCenter);
       calendarTable.getColumn("목").setCellRenderer(celAlignCenter);
       calendarTable.getColumn("금").setCellRenderer(celAlignCenter);
       calendarTable.getColumn("토").setCellRenderer(celAlignCenter);
      
    }//GEN-LAST:event_calendarBtnActionPerformed

    private void todolistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todolistBtnActionPerformed
       titleText.setText("TODO LIST");
       todoListPanel.setVisible(true); 
    }//GEN-LAST:event_todolistBtnActionPerformed

    private void hideBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideBtnActionPerformed
       titleText.setText(" ");
       timePanel.setVisible(false); //표 가리기
       cafeteriaPanel.setVisible(false); //표 가리기
       calendarPanel.setVisible(false); //표 가리기
       todoListPanel.setVisible(false); 
    }//GEN-LAST:event_hideBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private design.RoundedButton cafeteriaBtn;
    private javax.swing.JPanel cafeteriaPanel;
    private javax.swing.JTable cafeteriaTable;
    private design.RoundedButton calendarBtn;
    private javax.swing.JPanel calendarPanel;
    private javax.swing.JTable calendarTable;
    private design.RoundedButton hideBtn;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel mypage_id;
    private design.PanelBorder panelBorder1;
    private design.PanelBorder panelBorder3;
    private design.PanelGradiente panelGradiente1;
    private javax.swing.JPanel timePanel;
    private javax.swing.JTable timeTable;
    private design.RoundedButton timesheduleBtn;
    private javax.swing.JLabel titleText;
    private javax.swing.JPanel todoListPanel;
    private design.RoundedButton todolistBtn;
    // End of variables declaration//GEN-END:variables
}
